language: objective-c
osx_image: xcode7.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8

install:
  - carthage bootstrap --platform iOS

script:
  - set -o pipefail
  - xcodebuild test -scheme AlamofireAdapter -destination 'name=iPhone 6,OS=9.1' | xcpretty -c

notifications:
  email: false

